:repository-owner: arduino-libraries
:repository-name: Ethernet

= {repository-name} Library for Arduino =

image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml/badge.svg["Check Arduino status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml/badge.svg["Compile Examples status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml/badge.svg["Spell Check status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml"]

With the Arduino Ethernet Shield, this library allows an Arduino board to connect to the internet.



The original version of this library doesn't allow for a UDP Broadcast to be sent.  This version adds the necessary
"glue" to make that work correctly and adds two user facing functions to enable this functionality: 

EthernetUDP::beginPacketBroadcast(uint16_t port);

EthernetUDP::endPacket_RAW();


An example is also added to show the usage, which looks like this:

    Udp.beginPacketBroadcast(broadcastPort);
    Udp.write(Buffer);
    Udp.endPacket_RAW();




For more information about this library please visit us at
https://www.arduino.cc/en/Reference/{repository-name}

== License ==

Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
